plank:
  job_url_prefix_config:
    '*': "http://status-prow.apps.workspace.maistra.test/"
  default_decoration_configs:
    '*':
      timeout: 4h
      grace_period: 15s
      utility_images:
        clonerefs: "gcr.io/k8s-prow/clonerefs:v20200910-8c70361b39"
        initupload: "gcr.io/k8s-prow/initupload:v20200910-8c70361b39"
        entrypoint: "gcr.io/k8s-prow/entrypoint:v20200910-8c70361b39"
        sidecar: "gcr.io/k8s-prow/sidecar:v20200910-8c70361b39"
      gcs_configuration:
        path_strategy: explicit
        bucket: "ike-prow-logs"
      gcs_credentials_secret: "gcs-credentials"
